homeassistant:
  name: ZZ9 Plural Z Alpha
  latitude: 39.632321999999995
  longitude: -105.131914
#  unit_system: imperial
  time_zone: America/Denver

switch:
  platform: rpi_gpio
  ports:
    4: Front - North
    17: Front - South
    27: Back - South
    22: Back - North
    23: Back - Garden
  invert_logic: true

sensor:
  platform: forecast
  api_key: !secret forecast_api_key
  monitored_conditions:
    - temperature
    - humidity
    - precip_intensity
    - precip_probability

automation: !include_dir_list automation

input_slider: !include input_sliders.yaml

input_boolean: !include input_booleans.yaml

script: !include_dir_named scripts

logger:
  default: error
  logs:
    homeassistant.components.automation: debug
    homeassistant.components.script: debug
    homeassistant.components.switch: debug

sun:

logbook:

history:

frontend:
