alias: Back - Garden
trigger:
  platform: time
  hours:
    - 1
    - 8
    - 20
  minutes: 30
action:
  - service: switch.turn_on
    data:
      entity_id: swich.back_garden
  - service: script.delay_zone
  - service: switch.turn_off
    data:
      entity_id: switch.back_garden