alias: Back - South
trigger:
  platform: time
  hours:
    - 2
    - 9
    - 21
  minutes: 0
action:
  - service: switch.turn_on
    data:
      entity_id: swich.back_south
  - service: script.delay_zone
  - service: switch.turn_off
    data:
      entity_id: switch.back_south