alias: Back - North
trigger:
  platform: template
  value_template: >
    {{
      now.weekday() % 2 == 0
      and now.hour in [3, 20]
      and now.minute == 30
    }}
action:
  - service: switch.turn_on
    data:
      entity_id: swich.back_north
  - service: script.delay_zone
  - service: switch.turn_off
    data:
      entity_id: switch.back_north