alias: Back - South
trigger:
  platform: time
  hour: 1, 7, 21
  minute: 30
action:
  - service: switch.turn_on
    data:
      entity_id: swich.back_south
  - service: script.delay_zone
  - service: switch.turn_off
    data:
      entity_id: switch.back_south