alias: Back - Garden
trigger:
  platform: template
  value_template: >
    {{
      now.hour in [1, 8, 21]
      and now.minute == 30
    }}
action:
  - service: switch.turn_on
    data:
      entity_id: swich.back_garden
  - service: script.delay_zone
  - service: switch.turn_off
    data:
      entity_id: switch.back_garden