alias: Back - Garden
trigger:
  platform: template
  value_template: >
    {{
      now.hour in [1, 8, 21]
      and now.minute == 30
    }}
action:
  - service: script.delay_zone
    data:
      valve_id: 'switch.back__garden'
