alias: Clear Flags
trigger:
  platform: state
  entity_id:
    - input_boolean.hot_today
    - input_boolean.cold_today
    - input_boolean.might_rain_today
    - input_boolean.rained_today
  state: 'on'
  for:
    hours: 10
action:
  service: input_boolean.turn_off
  data_template:
    entity_id: {{ trigger.entity_id }}
