alias: Front - South
trigger:
  platform: template
  value_template: >
    {{
      now.weekday() % 2 == 1
      and now.hour in [3, 20]
      and now.minute == 0
    }}
action:
  - service: script.delay_zone
    data:
      valve_id: 'switch.back__garden'