alias: Front - North
trigger:
  platform: template
  value_template: >
    {{
      now.weekday() % 2 == 1
      and now.hour in [3, 20]
      and now.minute == 30
    }}
action:
  - service: script.run_zone
    data:
      valve_id: 'switch.front__north'