alias: Front - South
trigger:
  platform: template
  value_template: >
    {{
      now.weekday() % 2 == 1
      and now.hour in [3, 20]
      and now.minute == 0
    }}
action:
  - service: switch.turn_on
    data:
      entity_id: swich.front_south
  - service: script.delay_zone
  - service: switch.turn_off
    data:
      entity_id: switch.front_south