alias: Rained
trigger:
  platform: template
  value_template: >
    {{
      states.sensor.sensor.weather_precip_probability.state >= states.input_slider.consider_might_rain.state
    }}
action:
  service: input_boolean.turn_on
  data:
    entity_id: input_boolean.might_rain_today