alias: Might Rain
trigger:
  platform: template
  value_template: >
    {{
      (states.sensor.weather_precip_probability.state | float) >= (states.input_slider.consider_might_rain.state | float)
    }}
action:
  service: input_boolean.turn_on
  data:
    entity_id: input_boolean.might_rain_today